config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

Rails.application.routes.draw do
  get '/', to: 'searches#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :price_per_night, :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to flat_path
    else
      render :new
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.delete
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :photo_url)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    redirect_to flats_path if params[:query].empty?
    @flats = Flat.where("name LIKE '%#{params[:query]}%'")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(element) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, class: "form-group" %>
  <%= f.input :address, class: "form-group" %>
  <%= f.input :description, class: "form-group" %>
  <%= f.input :photo_url, class: "form-group" %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit class: "btn btn-outline-warning"%>
<% end %>

app/views/flats/edit.html.erb
<img src="<%= @flat.photo_url %>" class="banner">

<div class="form-container">
  <div class="form-box">
    <h1><%= @flat.name %></h1>
    <%= render "form", element: @flat %>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container">
  <h1>All our flats(<%= Flat.all.count %>)</h1>
  <% @flats.each_slice(3)  do |flats| %>
    <div class="row">
    <% flats.each  do |flat| %>
      <div class="card" style="width: 22rem;">
          <img src= "<%= flat.photo_url %>" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%= flat.name %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= flat.address%></h6>
            <p class="card-text">🧍 <%= flat.number_of_guests %> &nbsp;&nbsp;&nbsp;&nbsp; 💵 <%= flat.price_per_night %></p>
          </div>

          <div class="card-footer text-muted d-flex justify-content-around">
            <%= link_to "More info", flat_path(flat), class: "text-warning" %>
            <div>
              <%= link_to "Edit", edit_flat_path(flat), class: "text-secondary" %>
              &nbsp;||&nbsp;
              <%= link_to "🗑", flat_path(flat), method: :delete, data: { confirm: "Are you sure?" }, class: "text-secondary" %>
            </div>
          </div>
        </div>
    <% end %>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<img src="https://source.unsplash.com/X5BWooeO4Cw/3648×5472" class="banner">

<div class="form-container">
  <div class="form-box">
    <h1>New flat</h1>
    <%= render "form", element: @flat %>
  </div>
</div>

app/views/flats/show.html.erb
<img src="<%= @flat.photo_url %>" class="banner">

<div class="flat-container">
  <div class="flat-info">
    <div class="info-card">
      <h2><%= @flat.name %></h2>
      <p><%= @flat.address %></p>
    </div>

    <div class="info-card">
      <h3>A bit more about this flat...</h3>
      <p><%= @flat.description %></p>
      <img src="https://source.unsplash.com/AFB6S2kibuk/4000×2667">
    </div>
  </div>

  <div class="flat-options">
    <div class="date-form">
      <div class="input-group mb-2 mr-sm-2">
        <div class="input-group-prepend">
          <div class="input-group-text">From:</div>
        </div>
        <input class="form-control" type="date" value="2011-08-19" id="example-date-input">
      </div>

      <div class="input-group mb-2 mr-sm-2">
        <div class="input-group-prepend">
          <div class="input-group-text">To:</div>
        </div>
        <input class="form-control" type="date" value="2011-08-19" id="example-date-input">
      </div>

      <button type="button" class="btn btn-warning btn-lg btn-block">Book</button>
    </div>

    <div class="info-card">
      <h3>Details</h3>
      <p>🧍 <%= @flat.number_of_guests %> &nbsp;&nbsp;&nbsp;&nbsp; 💵 <%= @flat.price_per_night %></p>
    </div>

    <div class="share-card">
      <p>Share</p>
      <div>
        <a href="">🅵</a>
        <a href="">🆃</a>
        <a href="">🅿</a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <%= link_to "✨ Simple Airbnb ✨", flats_path, class: "navbar-brand" %>
      <form action = "/", class="form-inline">
        <input class="form-control mr-sm-2" name="query" id= "query" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-info my-2 my-sm-0" type="search">Search</button>
        &nbsp;&nbsp;
        <%= link_to "Add a flat", new_flat_path, class: "btn btn-outline-warning" %>
      </form>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/searches/index.html.erb
<div class="container">
  <h1>All our flats</h1>
  <% @flats.each_slice(3)  do |flats| %>
    <div class="row">
    <% flats.each  do |flat| %>
      <div class="card" style="width: 22rem;">
          <img src= "<%= flat.photo_url %>" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%= flat.name %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= flat.address%></h6>
            <p class="card-text">🧍 <%= flat.number_of_guests %> &nbsp;&nbsp;&nbsp;&nbsp; 💵 <%= flat.price_per_night %></p>
          </div>

          <div class="card-footer text-muted d-flex justify-content-around">
            <%= link_to "More info", flat_path(flat), class: "text-warning" %>
            <div>
              <%= link_to "Edit", edit_flat_path(flat), class: "text-secondary" %>
              &nbsp;||&nbsp;
              <%= link_to "🗑", flat_path(flat), method: :delete, data: { confirm: "Are you sure?" }, class: "text-secondary" %>
            </div>
          </div>
        </div>
    <% end %>
    </div>
  <% end %>
</div>